### ISSUE TITLE
Support for PyPI dependencies that don't have precompiled wheels?

### ISSUE THREAD

**Issue by joshburkart** [TriggerMail/rules_pyz#2]
Hi!

Really interesting set of tools you've put together, and I'm eager to experiment with them.

One confusion for me is how to handle PyPI dependencies that don't get an automatic, correct `http_file` rule generated by `pip_generate`. I think this occurs when there isn't a precompiled `.whl` available in PyPI... E.g. if I just have `docopt` in my `requirements.txt` file, and try to follow the instructions in your `README`, I get the following in my generated `third_party/pypi/pypi_rules.bzl`:

```python
def pypi_repositories():
    native.http_file(
        name="pypi_docopt",
        url="***ERROR***/docopt-0.6.2-py2.py3-none-any.whl",
        sha256="0b670b24f445201c64d506dd6df020215003b0855d242574b2f90ed17592aa89",
    )
```

where I have `***ERROR***` in the `url` attribute since I ran with `-wheelURLPrefix '***ERROR***/'`. What should I do in this case? I noticed the `-wheelDir` arg, but I'm not sure how to use it productively.

Any help would be appreciated!

**Comment by joshburkart** [comment]
@evanj

**Comment by evanj** [comment]
Sorry this is pretty confusing. Here is what I do:

1. Create a directory somewhere: `mkdir wheels`
2. Run `bazel-bin/.../pip_generate_wrapper -wheerDir=wheels -wheelURLPrefix=https://something.../`
3. Upload `wheels` somewhere world readable. I use Google Cloud Storage, so something like: `gsutil -m rsync -a public-read wheels gs://some-global-bucket`

I'll try to add this to the README. Thanks!

**Comment by evanj** [comment]
(Longer term I'd love to figure out how to have it generate the rules to build the wheel from source when needed, but that will take a bit more)

**Comment by joshburkart** [comment]
The building from source thing is what #3 does, though!
